version: '3.4'
services:
  react-app:
    build: 
      context: '.'
      target: ${NODE_ENV}
      args: 
        NODE_ENV: ${NODE_ENV}
    image: wilo087/react-boilerplate
    ports:
      - "3080:80"
      - "3000:3000"
    tty: true
    volumes:
      - ./:/app
      # - /usr/share/zoneinfo/America/Santo_Domingo:/etc/localtime:ro
